- name: "Create directory"
  file:
    path: "{{ nginx_lb_config.dir }}"
    state: "directory"

- name: "Copy docker-compose file"
  template:
    src: ../templates/docker-compose.nginx.template.j2
    dest: "{{ nginx_lb_config.dir }}//docker-compose.nginx.yml"

- name: "Create and copy nginx.conf"
  template:
    src: ../templates/nginx.template.j2
    dest: "{{ nginx_lb_config.dir }}/nginx.conf"

- name: "Deploy nginx"
  community.docker.docker_compose_v2:
    project_src: "{{ nginx_lb_config.dir }}"
    build: "always"
    recreate: "always"
    files:
      - docker-compose.nginx.yml
