- name: "Update&Upgrade"
  apt:
    name: aptitude
    state: present
    update_cache: true

- name: "Install dependencies"
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - httperf
    - iptraf
    - nload
    - sysstat
